DROP TABLE IF EXISTS `tt`;

CREATE TABLE `tt` (
    `u8` TINYINT UNSIGNED,
    `u8nn` TINYINT UNSIGNED NOT NULL,
    `u16` SMALLINT UNSIGNED,
    `u16nn` SMALLINT UNSIGNED NOT NULL,
    `u32` INT UNSIGNED,
    `u32nn` INT UNSIGNED NOT NULL,
    `u64` BIGINT UNSIGNED,
    `u64nn` BIGINT UNSIGNED NOT NULL,
    `i8` TINYINT,
    `i8nn` TINYINT NOT NULL,
    `i16` SMALLINT,
    `i16nn` SMALLINT NOT NULL,
    `i32` INT,
    `i32nn` INT NOT NULL,
    `i64` BIGINT,
    `i64nn` BIGINT NOT NULL,
    `f32` FLOAT,
    `f32nn` FLOAT NOT NULL,
    `f64` REAL,
    `f64nn` REAL NOT NULL,
    `date` DATE,
    `date_nn` DATE NOT NULL,
    `time` TIME,
    `time_nn` TIME NOT NULL,
    `datetime` DATETIME,
    `datetime_nn` DATETIME NOT NULL,
    `timestamp` TIMESTAMP,
    `timestamp_nn` TIMESTAMP NOT NULL,
    `str` VARCHAR(255),
    `str_nn` VARCHAR(255) NOT NULL,
    `txt` TEXT,
    `txt_nn` TEXT NOT NULL,
    `blob` BLOB,
    `blob_nn` BLOB NOT NULL,
    `bool` TINYINT(1),
    `bool_nn` TINYINT(1) NOT NULL
);
